baseURL = 'https://domnek.de/'
languageCode = 'de'
title = 'Digitaler Garten'
theme = 'hugo-geekdoc'

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Rquired if you want to render robots.txt template
enableRobots.txt = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcodes or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[taxonomies]
  tag = 'tags'