name: Deploy Hugo site

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy website with rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --quiet --delete
        path: public/
        remote_path: /home/deploy/docker/appdata/nginx/content/hugo/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USER }}
        remote_port: ${{ secrets.PORT }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
