name: Deploy Hugo site

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-versions: 'latest'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secres.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        scripts: |
          rm -rf /home/users/dominik/docker/appdata/nginx/content/hugo/*
          cp -R public/* /home/users/dominik/docker/appdata/nginx/content/hugo/